### ISSUE TITLE
Attachment issue

### ISSUE THREAD

**Issue by ayshtmr** [dhruvagarwal/termailer#1]
if i have to attach a couple of attachments then i need to provide absolute paths for each attachment. Could you pls improve this feature

**Comment by dhruvagarwal** [comment]
yeah sure .. i was already working on it 
will be pushing it soon :+1:

**Comment by ayshtmr** [comment]
Could be better

**Comment by dhruvagarwal** [comment]
Better can be achieved at horizon. @ayushtomar

**Comment by ayshtmr** [comment]
Expand your horizon
